import type { Activity } from "@/types";

export const activities: Activity[] = [
  {
    slug: "intro-diving",
    name: "Intro Diving",
    basePriceUsd: 50,
    summary: "A beginner-friendly diving experience for first-time guests.",
    category: "Diving",
    highlights: ["Beginner-friendly", "Guide support"],
  },
  {
    slug: "professional-diving",
    name: "Professional Diving",
    basePriceUsd: 60,
    summary: "Guided dives for certified or experienced divers.",
    category: "Diving",
    highlights: ["Certified divers", "Red Sea sites"],
  },
  {
    slug: "snorkeling",
    name: "Snorkeling",
    basePriceUsd: 40,
    summary: "A relaxed Red Sea snorkeling trip for families and groups.",
    category: "Snorkeling",
    highlights: ["Family-friendly", "Reef views"],
  },
  {
    slug: "paradise-island",
    name: "Paradise Island",
    basePriceUsd: 30,
    summary: "A day trip to Paradise Island with sea activities.",
    category: "Island Trip",
    highlights: ["Beach time", "Boat day"],
  },
  {
    slug: "open-water-diver-course",
    name: "Open Water Diver Course",
    basePriceUsd: 350,
    summary: "Entry-level diver certification course.",
    category: "Course",
    highlights: ["Certification path", "Training sessions"],
  },
  {
    slug: "advanced-open-water-diver-course",
    name: "Advanced Open Water Diver Course",
    basePriceUsd: 300,
    summary: "Advanced certification course for certified divers.",
    category: "Course",
    highlights: ["Skill building", "Advanced dives"],
  },
  {
    slug: "private-boat",
    name: "Private Boat",
    basePriceUsd: 500,
    summary: "Private boat reservation for custom group trips.",
    category: "Private Trip",
    highlights: ["Custom plan", "Group-friendly"],
  },
  {
    slug: "orange-bay",
    name: "Orange Bay",
    basePriceUsd: 30,
    summary: "A Red Sea island day trip to Orange Bay.",
    category: "Island Trip",
    highlights: ["Island visit", "Clear water"],
  },
];
