import type { Activity } from "@/types";

export const activities: Activity[] = [
  {
    slug: "intro-diving",
    name: "Intro Diving",
    basePriceUsd: 50,
    pricingMode: "perPerson",
    shortDescription: "Your first breath underwater",
    detailedDescription:
      "A safe and exciting introduction to scuba diving in the Red Sea. No prior experience required — our team guides you step by step from the briefing to your first underwater moments. Perfect for beginners who want to try diving in shallow, clear water with full instructor support.",
    summary: "A beginner-friendly diving experience for first-time guests.",
    category: "Diving",
    highlights: [
      "No experience required",
      "Full instructor guidance",
      "Shallow, clear-water dive site",
      "All equipment included",
    ],
    image: "/images/activities/intro-diving.webp",
  },
  {
    slug: "professional-diving",
    name: "Professional Diving",
    basePriceUsd: 60,
    pricingMode: "perPerson",
    shortDescription: "Guided dives for certified divers",
    detailedDescription:
      "Explore the best dive sites Hurghada has to offer with an experienced guide. Designed for certified divers who want to experience the Red Sea's vibrant reefs, walls, and marine life. Each trip is planned around conditions and guest experience level.",
    summary: "Guided dives for certified or experienced divers.",
    category: "Diving",
    highlights: [
      "For certified divers",
      "Guided Red Sea dive sites",
      "Reef, wall, and drift dives",
      "Equipment available on request",
    ],
    image: "/images/activities/professional-diving.webp",
  },
  {
    slug: "snorkeling",
    name: "Snorkeling",
    basePriceUsd: 40,
    pricingMode: "perPerson",
    shortDescription: "Easy Red Sea snorkeling day",
    detailedDescription:
      "A relaxed snorkeling trip built for families, couples, and groups who want to enjoy the Red Sea from the surface. Visit shallow reefs with clear visibility, swim alongside colorful fish, and enjoy a full day on the water with snacks and support.",
    summary: "A relaxed Red Sea snorkeling trip for families and groups.",
    category: "Snorkeling",
    highlights: [
      "Family-friendly and beginner-safe",
      "Shallow reef access",
      "All snorkeling gear included",
      "Snacks and soft drinks provided",
    ],
    image: "/images/activities/snorkeling.webp",
  },
  {
    slug: "paradise-island",
    name: "Paradise Island",
    basePriceUsd: 30,
    pricingMode: "perPerson",
    shortDescription: "Island day with beach and sea",
    detailedDescription:
      "Spend a full day on Paradise Island — a famous Red Sea sand island with crystal-clear water, soft sand, and plenty of space to relax. Includes boat transfer, beach time, snorkeling stops, and lunch. Ideal for families, couples, and groups looking for a classic island escape.",
    summary: "A day trip to Paradise Island with sea activities.",
    category: "Island Trip",
    highlights: [
      "Boat transfer included",
      "Beach time and swimming",
      "Snorkeling stops along the way",
      "Lunch and soft drinks provided",
    ],
    image: "/images/activities/paradise-island.jpg",
  },
  {
    slug: "open-water-diver-course",
    name: "Open Water Diver Course",
    basePriceUsd: 350,
    pricingMode: "perPerson",
    shortDescription: "Start your diving journey",
    detailedDescription:
      "An entry-level training course that teaches the fundamentals of scuba diving through classroom sessions, confined-water practice, and open-water dives. By the end of the course you will have the skills and confidence to dive independently with a buddy.",
    summary: "Entry-level diver certification course.",
    category: "Course",
    highlights: [
      "Classroom, pool, and open-water training",
      "Full equipment during the course",
      "Small group sizes",
      "Internationally recognised curriculum",
    ],
    image: "/images/activities/openwater-divercourse.webp",
  },
  {
    slug: "advanced-open-water-diver-course",
    name: "Advanced Open Water Diver Course",
    basePriceUsd: 300,
    pricingMode: "perPerson",
    shortDescription: "Build your diving skills",
    detailedDescription:
      "Take your diving to the next level with advanced training that covers deeper dives, underwater navigation, and specialty skills. Designed for certified divers who want to expand their comfort zone and explore more challenging sites.",
    summary: "Advanced certification course for certified divers.",
    category: "Course",
    highlights: [
      "Builds on existing certification",
      "Deep and navigation dives",
      "Specialty skill modules",
      "Small group instruction",
    ],
    image: "/images/activities/advanced-openwater-divercourse.webp",
  },
  {
    slug: "private-boat",
    name: "Private Boat",
    basePriceUsd: 500,
    pricingMode: "flat",
    shortDescription: "Your own boat for the day",
    detailedDescription:
      "Reserve a private boat for your group and design your own Red Sea day. Choose your stops — diving, snorkeling, island visits, or simply cruising. Ideal for families, celebrations, and small groups who want privacy and flexibility on the water.",
    summary: "Private boat reservation for custom group trips.",
    category: "Private Trip",
    highlights: [
      "Full boat exclusively for your group",
      "Custom itinerary — you choose the stops",
      "Captain and crew included",
      "Flat price, not charged per guest",
    ],
    image: "/images/activities/private-boat.webp",
  },
  {
    slug: "orange-bay",
    name: "Orange Bay",
    basePriceUsd: 30,
    pricingMode: "perPerson",
    shortDescription: "Relaxing island-style Red Sea trip",
    detailedDescription:
      "A chilled-out island trip to Orange Bay with its shallow turquoise water, wooden pier, and relaxed beach vibe. Includes boat transfer, beach access, soft drinks, and time to swim, sunbathe, or simply enjoy the view.",
    summary: "A Red Sea island day trip to Orange Bay.",
    category: "Island Trip",
    highlights: [
      "Boat transfer included",
      "Beach loungers and shaded areas",
      "Shallow, calm water for swimming",
      "Soft drinks included",
    ],
    image: "/images/activities/orange-bay.jpg",
  },
];
