services:
  db:
    image: postgres:16-alpine
    container_name: graquamarine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: graquamarine
      POSTGRES_USER: graquamarine_user
      POSTGRES_PASSWORD: graquamarine_local_password
    ports:
      - "5433:5432"
    volumes:
      - graquamarine_pgdata:/var/lib/postgresql/data

volumes:
  graquamarine_pgdata:
